<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Informacion</title>
    <link rel="stylesheet" href="assets/css/mainStyle.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav>
            <a href="login.php">inicio</a>
            <a href="#AboutOf">Acerca de</a>
            <a href="#Referencias">Referencias</a>
            <a href="#Contactos">Contactos</a>
        </nav>
        <section class="Encabezado">
            <h1>JJ services para todo gusto en madera</h1>
            <h2>Unico con pagina web</h2>
        </section>
        
        <!-- Recurso de la ola Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div class="wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>

    </header>
    <main>
        <section class="contenedor AboutServices" id="AboutOf">
            <h2 class="titulo">Nuestros servicios</h2>
            <div class="contenedorAboutUsInfo">
                <!-- Imagen de prueba -->
                <img src="assets/imagenes/Portada.jpg" alt="" class="imagenAboutUs">
                <div class="contenedorDescripcion">
                    <h3><span>1</span>Reparacion</h3>
                    <p>Nuestra especialidad es reparar muebles de casi todo tipo, no tires esos muebles que crees irreparables, inicia sesión o registrate para hacer una solicitud.</p>
                    <h3><span>2</span>Creacion</h3>
                    <p>Nada como unos hermosos muebles hechos a tu gusto, inicia sesión o registrate para hacer una solicitud.</p>
                </div>
            </div>
        </section>
        <section class="clientes contenedor" id="Referencias">
            <h2 class="titulo">Nuestros clientes</h2>
            <div class="cards">
                <div class="card">
                    <img src="assets/imagenes/Cliente1.jpg" alt="">
                    <div class="contenedorCard">
                        <h4>Jamilka Gil</h4>
                        <p>No me arrepiento haber contactado JJservices, quería hacer una reparación a una mesa pequeña, contaba con un presupuesto muy limitado, así que nadie queria hacer la reparación, pero JJservices tomo la reparación y encima no esperé que quedara tan bien.</p>
                    </div>
                </div>
                <div class="card">
                    <img src="assets/imagenes/Cliente2.jpg" alt="">
                    <div class="contenedorCard">
                        <h4>Laisa Almanzar</h4>
                        <p>Hacen hermosos diseños según tu presupuesto, solicité una mesa de 6 sillas en caoba, sobra decir lo hermoso de esa mesa y lo encantada que quedé con el resultado. JJservices es en quien pienzo para diseñar mis muebles.</p>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <div class="contenedorFooter" id="Contactos">
            <div class="contenedorInfo">
                <h4>Numero</h4>
                <p>829-347-3029</p>
            </div>
            <div class="contenedorInfo">
                <h4>Email</h4>
                <p>201804883@p.uapa.edu.do</p>
            </div>
        </div>
        <h2 class="propietario">&copy; Ing Jeferson Gil</h2>
    </footer>
</body>